### ISSUE TITLE
Supported Types for Queue

### ISSUE THREAD

**Issue by tomharmon** [SamedhG/Queue-API#5]
Added a StringQueue spec [here](https://github.com/SamedhG/Queue-API/commit/6308785ca64f8c9465c3eda574d407b584a7086c)

**Comment by brycedewitt** [comment]
@thomasharmon808 Just remind me again what the point of the StringQueue is?  Can't a normal Queue support any `Object` type (of which a string is a subclass)? 

Is the StringQueue supposed to just limit the types of objects it contains? I mean it would make sense to have IntQueue, FloatQueue or BooleanQueue since we can just store them as primitives, but since we're already wrapping Strings in objects, whats the upside of this?

**Comment by tomharmon** [comment]
Yeah so initially I had the same thoughts but I changed my mind after reading (painfully) all of the piazza posts Jan Vitek made and hearing what he said in my class section.

> Is the StringQueue supposed to just limit the types of objects it contains?

Yes. Jan said this was required during my class section.

As far as IntQueue etc, the assignment says only object and string are needed for queue:
"The Queue class should support normal push and pop operations, the values that need to be supported are Strings and Objects"

Implementing the String queue should be easy enough I hope. For ours, we only had to override certain methods to `exit(1)` when the desired operation shouldn't be supported (you gave an example of one case). And the rest of the methods can just call Array::method, casting the return value to String* if needed
@brycedewitt
